version: '3.4'

networks:
    podewitz_local_net:
        ipam:
            config:
                - subnet: 172.25.0.0/16

secrets:
    ldap_ssl_key:
        file: ./SSLCertificates/local/podewitz/ldap/ldap.podewitz.local.key
    ldap_ssl_crt:
        file: ./SSLCertificates/local/podewitz/ldap/ldap.podewitz.local.crt
    lum_ssl_key:
        file: ./SSLCertificates/local/podewitz/lum/lum.podewitz.local.key
    lum_ssl_crt:
        file: ./SSLCertificates/local/podewitz/lum/lum.podewitz.local.crt
    paperless_ssl_key:
        file: ./SSLCertificates/local/podewitz/paperless/paperless.podewitz.local.key
    paperless_ssl_crt:
        file: ./SSLCertificates/local/podewitz/paperless/paperless.podewitz.local.crt
    root_ca_crt:
        file: ./SSLCertificates/rootCA.crt
    metabase_ssl_key:
        file: ./SSLCertificates/local/podewitz/metabase/metabase.podewitz.local.key
    metabase_ssl_crt:
        file: ./SSLCertificates/local/podewitz/metabase/metabase.podewitz.local.crt
    db-admin_ssl_key:
        file: ./SSLCertificates/local/podewitz/db-admin/db-admin.podewitz.local.key
    db-admin_ssl_crt:
        file: ./SSLCertificates/local/podewitz/db-admin/db-admin.podewitz.local.crt
    home_ssl_key:
        file: ./SSLCertificates/local/podewitz/podewitz.local.key
    home_ssl_crt:
        file: ./SSLCertificates/local/podewitz/podewitz.local.crt
    ldap-admin_ssl_key:
        file: ./SSLCertificates/local/podewitz/ldap-admin/ldap-admin.podewitz.local.key
    ldap-admin_ssl_crt:
        file: ./SSLCertificates/local/podewitz/ldap-admin/ldap-admin.podewitz.local.crt
    airflow_ssl_key:
        file: ./SSLCertificates/local/podewitz/airflow/airflow.podewitz.local.key
    airflow_ssl_crt:
        file: ./SSLCertificates/local/podewitz/airflow/airflow.podewitz.local.crt
    airflow-flower_ssl_key:
        file: ./SSLCertificates/local/podewitz/airflow/airflow-flower.podewitz.local.key
    airflow-flower_ssl_crt:
        file: ./SSLCertificates/local/podewitz/airflow/airflow-flower.podewitz.local.crt
    budget_ssl_key:
        file: ./SSLCertificates/local/podewitz/budget/budget.podewitz.local.key
    budget_ssl_crt:
        file: ./SSLCertificates/local/podewitz/budget/budget.podewitz.local.crt
    home-assistant_ssl_key:
        file: ./SSLCertificates/local/podewitz/home-assistant/home-assistant.podewitz.local.key
    home-assistant_ssl_crt:
        file: ./SSLCertificates/local/podewitz/home-assistant/home-assistant.podewitz.local.crt

    db_admin_pw:
        file: ./init/db/config/db_admin_pw
    airflow_fernet_key:
        file: ./init/airflow/config/fernet_key
