version: '3.4'
services:
    etcd:
        image: etcd
        build: ./etcd-docker
        container_name: etcd
        restart: unless-stopped
        domainname: podewitz.local
        hostname: etcd
        #healthcheck:
        ports:
            - "2379:2379"
            - "2380:2380"
        volumes:
            - etcd-data:/etcd-data
        secrets:
            - etcd_ssl_key
            - etcd_ssl_crt
            - root_crt
        networks:
            podewitz_local_net:
                ipv4_address: 172.25.0.2
networks:
    podewitz_local_net:
        ipam:
            config:
                - subnet: 172.25.0.0/16

volumes:
    etcd-data:
        name: etcd-data

secrets:
    etcd_ssl_key:
        file: ./SSLCertificates/local/podewitz/etcd/etcd.podewitz.local.key
    etcd_ssl_crt:
        file: ./SSLCertificates/local/podewitz/etcd/etcd.podewitz.local.crt
    root_crt:
        file: ./SSLCertificates/rootCA.crt

