version: '3.4'
services:
    dnsmasq:
        image: npodewitz/dnsmasq:latest
        #build: ./dnsmasq-docker
        container_name: dnsmasq
        restart: unless-stopped
        hostname: dnsmasq.${DOMAINNAME}
        healthcheck:
            test: ["CMD", "nc" , "-w", "1", "dnsmasq.podewitz.local", "53"]
            interval: 30s
            timeout: 10s
            retries: 5
        cap_add:
            - NET_ADMIN
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"
        secrets:
            - source: etcd_client_ssl_key
              target: /etc/ssl/etcd_client.key
            - source: etcd_client_ssl_crt
              target: /etc/ssl/etcd_client.crt
            - source: root_ca_crt
              target: /etc/ssl/root_ca.crt
        env_file:
            - docker-compose.base.env
        #environment:
        networks:
            podewitz_local_net:
                aliases:
                    - dnsmasq.${DOMAINNAME}
                ipv4_address: 172.25.0.100
        depends_on:
            - etcd


