version: '3.4'

services:
  budget:
    image: npodewitz/budget:${DOCKER_BUDGET_VERSION}
    #build: ./backend
    container_name: budget
    hostname: budget.${DOMAINNAME}
    restart: unless-stopped
    expose:
      - 8000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 30s
      timeout: 10s
      retries: 5
    # volumes:
    # - /path/to/another/arbitrary/place:/data
    env_file:
      - docker-compose.base.env
    environment:
      # - DB_TYPE=sqlite
      # - SQLITE_DB_PATH=budget.sqlite
      - ALLOWED_HOSTS=*
      - LANGUAGE_CODE=de
      - TIME_ZONE=Europe/Berlin
      - DB_TYPE=postgres
      - DB_NAME=budget-db
      - DB_USER=budget
      - DB_PW=ypqmt4ffp3
      - DB_HOST=db.podewitz.local
      - DB_PORT=5432
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.budget-backend.rule=Host(`budget.${DOMAINNAME}`)"
      - "traefik.http.routers.budget-backend.tls=true"
    networks:
      podewitz_local_net:
        aliases:
          - budget.${DOMAINNAME}
        ipv4_address: 172.25.0.14
    depends_on:
      - reverse-proxy
      - db
      - db-admin
