version: '3.4'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy:alpine
        container_name: nginx-proxy
        restart: unless-stopped
        hostname: nginx-proxy.${REALM}
        #healthcheck
        ports:
            - "80:80"
            - "443:443"
        env_file:
            - docker-compose.base.env
        environment:
            - DEFAULT_HOST=lum.${REALM}
        secrets:
            - source: lum_ssl_key
              target: /etc/nginx/certs/lum.${REALM}.key
            - source: lum_ssl_crt
              target: /etc/nginx/certs/lum.${REALM}.crt
            - source: paperless_ssl_key
              target: /etc/nginx/certs/paperless.${REALM}.key
            - source: paperless_ssl_crt
              target: /etc/nginx/certs/paperless.${REALM}.crt
            - source: e3w_ssl_key
              target: /etc/nginx/certs/e3w.${REALM}.key
            - source: e3w_ssl_crt
              target: /etc/nginx/certs/e3w.${REALM}.crt
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            podewitz_de_net:
                aliases:
                    - nginx-proxy.${REALM}
                ipv4_address: 172.25.0.7

