version: '3.4'

services:
    paperless:
        image: jonaswinkler/paperless-ng:${DOCKER_PAPERLESS_VERSION}
        #build: ./paperless-docker
        container_name: paperless
        hostname: paperless.${DOMAINNAME}
        restart: unless-stopped
        #ports:
        #    - 8000:8000
        healthcheck:
            test: ["CMD", "curl" , "-f", "http://localhost:8000"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - paperless-media:/usr/src/paperless/media
            - /mnt/hdd/paperless_data/consume:/usr/src/paperless/consume
            - /mnt/hdd/paperless_data/export:/usr/src/paperless/export
            # Likewise, you can add a local path to mount a directory for
            # exporting. This is not strictly needed for paperless to
            # function, only if you're exporting your files: uncomment
            # it and fill in a local path if you know you're going to
            # want to export your documents.
            # - /path/to/another/arbitrary/place:/export
        env_file:
            - docker-compose.base.env
        #env_file:
        #    - ./services/docker-compose.paperless.env
        # The reason the line is here is so that the webserver that doesn't do
        # any text recognition and doesn't have to install unnecessary
        # languages the user might have set in the env-file by overwriting the
        # value with nothing.
        environment:
            - VIRTUAL_HOST=paperless.${DOMAINNAME}
            - VIRTUAL_PORT=80
            - VIRTUAL_ICON=library_books
            #- VIRTUAL_PROTO=https
            #- HTTPS_METHOD=noredirect
            - SERVER_HOSTNAME=paperless.${DOMAINNAME}
            - PAPERLESS_REDIS=redis://paperless-broker:6379
            - PAPERLESS_DBHOST=db
            - PAPERLESS_TIKA_ENABLED=1
            - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://paperless-gotenberg:3000
            - PAPERLESS_TIKA_ENDPOINT=http://paperless-tika:9998
            - PAPERLESS_TIME_ZONE=Europe/Berlin
            - PAPERLESS_OCR_LANGUAGES=deu eng spa
            - PAPERLESS_COR_LANGUAGE=deu
            - USERMAP_UID=1000
            - USERMAP_GID=1000
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.paperless.rule=Host(`paperless.${DOMAINNAME}`)"
            - "traefik.http.routers.paperless.tls=true"
        networks:
            podewitz_local_net:
                aliases:
                    - paperless.${DOMAINNAME}
                ipv4_address: 172.25.0.8
        depends_on:
            - reverse-proxy
            - db
            - paperless-broker
            - paperless-gotenberg
            - paperless-tika

    paperless-broker:
        image: redis:${DOCKER_PAPERLESS_REDIS_VERSION}
        container_name: paperless-broker
        hostname: paperless-broker.${DOMAINNAME}
        restart: unless-stopped
        networks:
          podewitz_local_net:
              aliases:
                  - paperless-broker.${DOMAINNAME}
              ipv4_address: 172.25.0.81

    paperless-gotenberg:
        image: thecodingmachine/gotenberg:${DOCKER_PAPERLESS_GOTENBERG_VERSION}
        container_name: paperless-gotenberg
        hostname: paperless-gotenberg.${DOMAINNAME}
        restart: unless-stopped
        environment:
            DISABLE_GOOGLE_CHROME: 1
        networks:
          podewitz_local_net:
              aliases:
                  - paperless-gotenberg.${DOMAINNAME}
              ipv4_address: 172.25.0.82

    paperless-tika:
        image: apache/tika:${DOCKER_PAPERLESS_TIKA_VERSION}
        container_name: paperless-tika
        hostname: paperless-tika.${DOMAINNAME}
        restart: unless-stopped
        networks:
          podewitz_local_net:
              aliases:
                  - paperless-tika.${DOMAINNAME}
              ipv4_address: 172.25.0.83

volumes:
    paperless-media:
        name: paperless-media
        labels:
            paperless-media.service_owner: "paperless"
