version: '3.8'
services:
    ldap:
        image: lldap/lldap:2023-11-05
        container_name: ldap
        restart: unless-stopped
        hostname: ldap.${DOMAINNAME}
        ports:
            # For LDAP
            #- "3890:3890"
            # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
            - "6360:6360"
            # For the web front-end
            - "17170:17170"
        volumes:
            - "./data/ldap:/data"
        secrets:
            - ldap_ssl_key
            - ldap_ssl_crt
            - ldap_jwt_secret
            - ldap_admin_pass
        env_file:
            - docker-compose.base.env
        environment:
            - UID=1000
            - GID=1000
            - TZ=Europe/Berlin
            - LLDAP_JWT_SECRET_FILE=/run/secrets/ldap_jwt_secret
            - LLDAP_LDAP_USER_PASS_FILE=/run/secrets/ldap_admin_pass
            - LLDAP_LDAP_BASE_DN=dc=podewitz,dc=local
            - LLDAP_LDAPS_OPTIONS__ENABLED=true
            - LLDAP_LDAPS_OPTIONS__CERT_FILE=/run/secrets/ldap_ssl_crt
            - LLDAP_LDAPS_OPTIONS__KEY_FILE=/run/secrets/ldap_ssl_key
            # You can also set a different database:
            # - LLDAP_DATABASE_URL=mysql://mysql-user:password@mysql-server/my-database
            # - LLDAP_DATABASE_URL=postgres://postgres-user:password@postgres-server/my-database
        networks:
            podewitz_local_net:
                aliases:
                    - ldap.${DOMAINNAME}
                ipv4_address: 172.25.0.3
