version: '3.4'

services:
    db-admin:
        image: dpage/pgadmin4:${DOCKER_PGADMIN_VERSION}
        #build: ./pgadmin-docker
        container_name: db-admin
        hostname: db-admin.${DOMAINNAME}
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl" , "--cacert", "/etc/ssl/root_ca.crt", "-f", "https://db-admin.podewitz.local:443"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - db-admin-data:/var/lib/pgadmin
        secrets:
            - source: etcd_client_ssl_key
              target: /etc/ssl/etcd_client.key
            - source: etcd_client_ssl_crt
              target: /etc/ssl/etcd_client.crt
            - source: root_ca_crt
              target: /etc/ssl/root_ca.crt
        env_file:
            - docker-compose.base.env
        environment:
            - VIRTUAL_HOST=db-admin.${DOMAINNAME}
            - VIRTUAL_PORT=80
            - PGADMIN_DEFAULT_EMAIL=nils.podewitz@googlemail.com
            - PGADMIN_DEFAULT_PASSWORD=TOCHANGE
        networks:
            podewitz_local_net:
                aliases:
                    - db.${DOMAINNAME}
                ipv4_address: 172.25.0.12
        depends_on:
            - etcd
            - ldap
            - nginx-proxy
            - db

