version: '3.4'
services:
    openldap-server:
        image: osixia/openldap:${DOCKER_OPENLDAP_VERSION}
        container_name: openldap-server
        restart: unless-stopped
        hostname: ldap.${DOMAINNAME}
        #healthcheck
        command: --copy-service
        ports:
            - "389:389"
            - "636:636"
        volumes:
            - openldap-config:/etc/ldap
            - openldap-data:/var/lib/ldap
            - ./conf/openldap-server/schema/sudo.schema:/container/service/slapd/assets/config/bootstrap/schema/sudo.schema
            - ./init/openldap-server/backup/ldap_dump_latest.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/02_ldap_dump.ldif
            - ./init/openldap-server/config/ldap_config.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/01_ldap_config.ldif
            - ./conf/openldap-server/env/def-env.yaml:/container/environment/01-custom/env.yaml
        secrets:
            - source: ldap_ssl_key
              target: /container/service/slapd/assets/certs/ldap_ssl.key
            - source: ldap_ssl_crt
              target: /container/service/slapd/assets/certs/ldap_ssl.crt
            - source: root_ca_crt
              target: /container/service/slapd/assets/certs/root_ca.crt
        environment:
            - LDAP_TLS_CRT_FILENAME=ldap_ssl.crt
            - LDAP_TLS_KEY_FILENAME=ldap_ssl.key
            - LDAP_TLS_CA_CRT_FILENAME=root_ca.crt
            - LDAP_ORGANISATION=Podewitz
            - LDAP_DOMAIN=${DOMAINNAME}
            - LDAP_RFC2307BIS_SCHEMA=true
            - LDAP_BACKEND=mdb
            - LDAP_TLS_ENFORCE=true
            - LDAP_TLS_VERIFY_CLIENT=try
        networks:
            podewitz_local_net:
                aliases:
                    - ldap.${DOMAINNAME}
                ipv4_address: 172.25.0.4

