version: '3.4'
services:
    ldap-admin:
        image: osixia/phpldapadmin:latest
        container_name: ldap-admin
        restart: unless-stopped
        hostname: ldap-admin.${DOMAINNAME}
        healthcheck:
            test: ["CMD-SHELL", "[ $$(pgrep -u www-data -c -f /usr/sbin/apache2) -gt 0 ] || exit 1"]
            interval: 30s
            timeout: 10s
            retries: 5
        command: --copy-service
        expose:
            - "80"
        secrets:
            - ldap_ssl_key
            - ldap_ssl_crt
            - root_ca_crt
        env_file:
            - docker-compose.base.env
        environment:
            PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'ldaps://ldap.podewitz.local:636': [{'server': [{'port': 0}]}]}]"
            PHPLDAPADMIN_HTTPS: "false"
            #VIRTUAL_HOST: "ldap-admin.${DOMAINNAME}"
            #VIRTUAL_PORT: "80"
            #VIRTUAL_ICON: "folder_shared"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.ldap-admin.rule=Host(`ldap-admin.${DOMAINNAME}`)"
            - "traefik.http.routers.ldap-admin.tls=true"
        networks:
            podewitz_local_net:
                aliases:
                    - ldap-admin.${DOMAINNAME}
                ipv4_address: 172.25.0.5
        depends_on:
            - ldap
            - reverse-proxy

