version: '3.4'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy:alpine
        container_name: nginx-proxy
        restart: unless-stopped
        hostname: nginx-proxy.${DOMAINNAME}
        #healthcheck
        ports:
            - "80:80"
            - "443:443"
        env_file:
            - docker-compose.base.env
        environment:
            - DEFAULT_HOST=${DOMAINNAME}
        secrets:
            - source: lum_ssl_key
              target: /etc/nginx/certs/lum.${DOMAINNAME}.key
            - source: lum_ssl_crt
              target: /etc/nginx/certs/lum.${DOMAINNAME}.crt
            - source: paperless_ssl_key
              target: /etc/nginx/certs/paperless.${DOMAINNAME}.key
            - source: paperless_ssl_crt
              target: /etc/nginx/certs/paperless.${DOMAINNAME}.crt
            - source: e3w_ssl_key
              target: /etc/nginx/certs/e3w.${DOMAINNAME}.key
            - source: e3w_ssl_crt
              target: /etc/nginx/certs/e3w.${DOMAINNAME}.crt
            - source: metabase_ssl_key
              target: /etc/nginx/certs/metabase.${DOMAINNAME}.key
            - source: metabase_ssl_crt
              target: /etc/nginx/certs/metabase.${DOMAINNAME}.crt
            - source: db-admin_ssl_key
              target: /etc/nginx/certs/db-admin.${DOMAINNAME}.key
            - source: db-admin_ssl_crt
              target: /etc/nginx/certs/db-admin.${DOMAINNAME}.crt
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./init/proxy/config/default:/etc/nginx/vhost.d/default
        networks:
            podewitz_local_net:
                aliases:
                    - nginx-proxy.${DOMAINNAME}
                ipv4_address: 172.25.0.7

