version: '3.8'
services:
    home:
        image: npodewitz/landing_page:latest
        container_name: home
        restart: unless-stopped
        hostname: home.${DOMAINNAME}
        #healthcheck
        env_file:
            - docker-compose.base.env
        environment:
            - VIRTUAL_HOST=${DOMAINNAME}
            - VIRTUAL_PORT=8000
            - BLACKLIST_NAMES=home
            - DOCKER_HOST=unix://tmp/docker.sock
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.home.rule=Host(`${DOMAINNAME}`)"
            - "traefik.http.routers.home.tls=true"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            podewitz_local_net:
                aliases:
                    - home.${DOMAINNAME}
                ipv4_address: 172.25.0.21
        depends_on:
          - reverse-proxy

