version: '3.4'

services:
    paperless:
        image: npodewitz/paperless:latest
        #build: ./paperless-docker
        container_name: paperless
        hostname: paperless.${DOMAINNAME}
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl" , "--cacert", "/etc/ssl/root_ca.crt", "-f", "https://paperless.podewitz.local:443"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - paperless-data:/usr/src/paperless/data
            - paperless-media:/usr/src/paperless/media
            - ./consume:/consume
            # Likewise, you can add a local path to mount a directory for
            # exporting. This is not strictly needed for paperless to
            # function, only if you're exporting your files: uncomment
            # it and fill in a local path if you know you're going to
            # want to export your documents.
            # - /path/to/another/arbitrary/place:/export
        secrets:
            - source: etcd_client_ssl_key
              target: /etc/ssl/etcd_client.key
            - source: etcd_client_ssl_crt
              target: /etc/ssl/etcd_client.crt
            - source: root_ca_crt
              target: /etc/ssl/root_ca.crt
            - source: paperless_ssl_key
              target: /etc/ssl/paperless.podewitz.local.key
            - source: paperless_ssl_crt
              target: /etc/ssl/paperless.podewitz.local.crt
        env_file:
            - docker-compose.base.env
        #env_file:
        #    - ./services/docker-compose.paperless.env
        # The reason the line is here is so that the webserver that doesn't do
        # any text recognition and doesn't have to install unnecessary
        # languages the user might have set in the env-file by overwriting the
        # value with nothing.
        environment:
            - VIRTUAL_HOST=paperless.${DOMAINNAME}
            - VIRTUAL_PORT=80
            #- VIRTUAL_PROTO=https
            #- HTTPS_METHOD=noredirect
            - SERVER_HOSTNAME=paperless.${DOMAINNAME}
        #command: ["runserver", "--insecure", "--noreload", "0.0.0.0:8080"]
        networks:
            podewitz_local_net:
                aliases:
                    - paperless.${DOMAINNAME}
                ipv4_address: 172.25.0.8
        depends_on:
            - etcd
            - openldap-server
            - nginx-proxy


