version: '3.4'

services:
    db:
        image: postgres:${DOCKER_POSTGRES_VERSION}
        #build: ./postgres-docker
        container_name: db
        hostname: db.${DOMAINNAME}
        restart: unless-stopped
        healthcheck:
        #    test: ["CMD", "curl" , "--cacert", "/etc/ssl/root_ca.crt", "-f", "https://paperless.podewitz.local:443"]
            test: ["CMD", "pg_isready", "-U", "admin"]
            interval: 30s
            timeout: 10s
            retries: 5
        ports:
                - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
        secrets:
            - source: etcd_client_ssl_key
              target: /etc/ssl/etcd_client.key
            - source: etcd_client_ssl_crt
              target: /etc/ssl/etcd_client.crt
            - source: root_ca_crt
              target: /etc/ssl/root_ca.crt
            - db_admin_pw
        env_file:
            - docker-compose.base.env
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD_FILE=/run/secrets/db_admin_pw
        networks:
            podewitz_local_net:
                aliases:
                    - db.${DOMAINNAME}
                ipv4_address: 172.25.0.10
        depends_on:
            - etcd
            - ldap

