version: '3.4'
services:
    phpldapadmin:
        image: osixia/phpldapadmin:latest
        container_name: phpldapadmin
        restart: unless-stopped
        hostname: phpldapadmin.${REALM}
        #healthcheck:
        #    test: ["CMD", "curl" , "-f", "http://paperless.podewitz.local:80"]
        #    interval: 30s
        #    timeout: 10s
        #    retries: 5
        command: --copy-service
        #ports:
        #    - "8080:80"
        secrets:
            - addc_ssl.key
            - addc_ssl.crt
            - root_ca.crt
        env_file:
            - docker-compose.base.env
        environment:
            PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'ldaps://addc.podewitz.de:389': [{'server': [{'port': 0}]}]}]"
            PHPLDAPADMIN_HTTPS: "false"
            VIRTUAL_HOST: "phpldapadmin.${REALM}"
            VIRTUAL_PORT: "80"
        networks:
            podewitz_de_net:
                aliases:
                    - phpldapadmin.${REALM}
                ipv4_address: 172.25.0.5
        depends_on:
            - addc
            - nginx-proxy

