[[tls.certificates]]
    certFile = "/etc/traefik/certs/ldap-admin.crt"
    keyFile = "/etc/traefik/certs/ldap-admin.key"

[[tls.certificates]]
    certFile = "/etc/traefik/certs/metabase.crt"
    keyFile = "/etc/traefik/certs/metabase.key"

[[tls.certificates]]
    certFile = "/etc/traefik/certs/lum.crt"
    keyFile = "/etc/traefik/certs/lum.key"

[[tls.certificates]]
    certFile = "/etc/traefik/certs/paperless.crt"
    keyFile = "/etc/traefik/certs/paperless.key"

[[tls.certificates]]
    certFile = "/etc/traefik/certs/db-admin.crt"
    keyFile = "/etc/traefik/certs/db-admin.key"

[[tls.certificates]]
    certFile = "/etc/traefik/certs/home.crt"
    keyFile = "/etc/traefik/certs/home.key"

[[tls.certificates]]
    certFile = "/etc/traefik/certs/airflow.crt"
    keyFile = "/etc/traefik/certs/airflow.key"

[[tls.certificates]]
    certFile = "/etc/traefik/certs/airflow-flower.crt"
    keyFile = "/etc/traefik/certs/airflow-flower.key"

[[tls.certificates]]
    certFile = "/etc/traefik/certs/budget.crt"
    keyFile = "/etc/traefik/certs/budget.key"

[[tls.certificates]]
    certFile = "/etc/traefik/certs/home-assistant.crt"
    keyFile = "/etc/traefik/certs/home-assistant.key"

[[tls.certificates]]
    certFile = "/etc/traefik/certs/simple-expenses.crt"
    keyFile = "/etc/traefik/certs/simple-expenses.key"